export const PATHS = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_VENDOR: '/register/vendor',
  FORGOT_PASSWORD: '/forgot-password',
  COUPON: '/coupon',
  DASHBOARD: '/dashboard',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:productId',
  PRODUCT_PAGE: '/product/:productId',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PAYMENT: '/payment',
  ORDER_SUCCESS: '/order-success',
  ORDERS: '/orders',
  TERMS: '/terms',
  ABOUT: '/about',
  CONTACT: '/contact',
  // Admin / Vendor Routes
  ADMIN_ORDERS: '/dashboard/orders',
  ADMIN_ORDER_DETAILS: '/dashboard/orders/:orderId',
  ADMIN_SCHEDULE: '/dashboard/schedule',
  ADMIN_PRODUCTS: '/dashboard/products',
  ADMIN_REPORTS: '/dashboard/reports',
  ADMIN_SETTINGS: '/dashboard/settings',
  ADMIN_USERS: '/dashboard/settings/users',

  ORDER_DETAILS: '/orders/:orderId',
  TRACK_RENTAL: '/track/:orderId',
  PROFILE: '/profile',
  INVOICE: '/invoice/:orderId',
  ADMIN_DASHBOARD: '/admin/dashboard',

};
