export const PATHS = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_VENDOR: '/register/vendor',
  FORGOT_PASSWORD: '/forgot-password',
  COUPON: '/coupon',
  DASHBOARD: '/dashboard',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:productId',
  PRODUCT_PAGE: '/product/:productId',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PAYMENT: '/payment',
  ORDER_SUCCESS: '/order-success',
  ORDERS: '/orders',
  TERMS: '/terms',
  ABOUT: '/about',
  CONTACT: '/contact',
  ORDER_DETAILS: '/orders/:orderId',
  TRACK_RENTAL: '/track/:orderId',
  PROFILE: '/profile',
};
